---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update bundler
  - gem --version
  - bundle -v

stages:
  - unit
  - if: tag !~ ^v\d
    name: acceptance
  - if: tag =~ ^v\d
    name: deploy

script: 'bundle exec rake $CHECK'

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.9
    env: CHECK="validate lint strings:generate reference" PUPPET_GEM_VERSION="~> 5"
    stage: unit
  - rvm: 2.5.7
    env: CHECK="validate lint strings:generate reference" PUPPET_GEM_VERSION="~> 6"
    stage: unit
  - rvm: 2.4.9
    env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 5"
    stage: unit
  - rvm: 2.4.9
    env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
    stage: unit
  - rvm: 2.5.7
    env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 6"
    stage: unit
  - rvm: 2.5.7
    env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
    stage: unit
  - rvm: 2.4.9
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5 CHECK="beaker"
    bundler_args:
    stage: acceptance
  - rvm: 2.5.7
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6 CHECK="beaker"
    bundler_args:
    stage: acceptance
  - rvm: 2.5.7
    services: docker
    env: BEAKER_set="centos-8" BEAKER_PUPPET_COLLECTION=puppet6 CHECK="beaker"
    bundler_args:
    stage: acceptance
  - rvm: 2.5.7
    services: docker
    env: BEAKER_set="debian-10" BEAKER_PUPPET_COLLECTION=puppet6 CHECK="beaker"
    bundler_args:
    stage: acceptance
  - rvm: 2.5.7
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6 CHECK="beaker"
    bundler_args:
    stage: acceptance
  - env: DEPLOY_TO_FORGE=yes
    stage: deploy
  allow_failures:
  - rvm: 2.4.9
    env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
  - rvm: 2.5.7
    env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"

branches:
  only:
    - master
    - /^v\d/

notifications:
  email: false

deploy:
  provider: puppetforge
  user: ghoneycutt
  password:
    secure: "bHE9oH8hkd9XqfQQ6M5wnoQ3ZU4NSR0pG2jkcDZPljA1ycDPUR2XRzkNdb6YfFjQjx/JqUJ9CFg9cYLmKYvfHS1vvOscvmj9oKySV4v1QRG1k57j16Eevs0HV6Dif371XBE+R6IdPodwEalsjIyMkIV4z3zvXrg46h6xfjLK78U="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
